#*******************************************************************************
#
#  Dockerfile to build image with all the tools to build Maiko for cygwin,
#  including cygwin itself plus a new build of SDL
#
#  Copyright 2023 by Interlisp.org
#
#  Frank Halasz 2023-06-08
#
# ******************************************************************************

FROM mcr.microsoft.com/windows/server:ltsc2022
SHELL ["powershell", "-command"]
# Install cygwin
COPY setup-x86_64.exe .
RUN [System.Environment]::SetEnvironmentVariable('CYGWIN','winsymlinks'); Unblock-File .\setup-x86_64.exe; Start-Process .\setup-x86_64.exe -Wait -ArgumentList @('"--root"', '".\cygwin"', '"--quiet-mode"', '"--no-admin"', '"--wait"', '"--no-shortcuts"', '"--no-write-registry"',  '"--verbose"', '"--site"', '"http://www.gtlib.gatech.edu/pub/cygwin/"', '"--packages"', '"nano,binutils,make,cmake,gcc,clang"')
RUN .\cygwin\bin\bash -login -c 'sed -i -e "s/^none/#none/" /etc/fstab; echo "none / cygdrive binary,posix=0,user 0 0" >>/etc/fstab'
# Build SDL
COPY sdl2.tar.gz sdl2.tar.gz
RUN .\cygwin\bin\bash -login -c 'cd / && tar xf /c/sdl2.tar.gz && mv SDL2-* sdl2'
RUN .\cygwin\bin\bash -login -c 'cd /sdl2 && ./configure && make && make install && rm -rf build'
ENTRYPOINT powershell

